--********
--Tablas
--********
CREATE TABLE TCCJCCTRORIGEN
( 
    FIORIGENID           SMALLINT  NOT NULL ,
    FCDESCRIPCION        CHAR(50)  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTCCJCCTRORIGEN PRIMARY KEY (FIORIGENID ASC)
)
GO



CREATE TABLE TCCJCCTRESTADOPOOL
( 
    FISTATUSPOOLID       SMALLINT  NOT NULL ,
    FCDESCRIPCION        CHAR(50)  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTCCJCCTRESTADOPOOL PRIMARY KEY (FISTATUSPOOLID ASC)
)
GO



CREATE TABLE TACJCCTRPOOLATENCION
( 
    FCEMPNOID            CHAR(6)  NOT NULL ,
    FCRUTAIMAGEN         CHAR(250)  NULL ,
    FISTATUSPOOLID       SMALLINT  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTACJCCTRPOOLATENCION PRIMARY KEY (FCEMPNOID ASC),
    CONSTRAINT XFKTCCJCCTRESTADOPOOL FOREIGN KEY (FISTATUSPOOLID) REFERENCES TCCJCCTRESTADOPOOL(FISTATUSPOOLID)
)
GO



CREATE INDEX XIF1TACJCCTRPOOLATENCION ON TACJCCTRPOOLATENCION
( 
    FISTATUSPOOLID        ASC
)
GO



CREATE TABLE TCCJCCTRUNIDADNEGOCIO
( 
    FIUNIDADNEGOCIOID    SMALLINT  NOT NULL ,
    FCDESCRIPCION        CHAR(50)  NULL ,
    FCRUTAIMAGEN         CHAR(250)  NULL ,
    FISTATUSUNDNEG       SMALLINT  NULL ,
    FLPRESTAMOS          BIT  NULL ,
    FCCOLOR              VARCHAR(30),
    FCZONA               VARCHAR(30),
    FCPREFIJO            CHAR(5),
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTCCJCCTRUNIDADNEGOCIO PRIMARY KEY (FIUNIDADNEGOCIOID ASC)
)
GO



CREATE TABLE TCCJCCTRTIPOFILA
( 
    FITIPOFILAID         SMALLINT  NOT NULL ,
    FCDESCRIPCION        CHAR(50)  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTCCJCCTRTIPOFILA PRIMARY KEY (FITIPOFILAID ASC)
)
GO



CREATE TABLE TCCJCCTRFILA
( 
    FIFILAID             SMALLINT  NOT NULL ,
    FIUNIDADNEGOCIOID    SMALLINT  NOT NULL ,
    FISTATUSFILA         SMALLINT  NULL ,
    FITIPOFILAID         SMALLINT  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTCCJCCTRFILA PRIMARY KEY (FIFILAID ASC,FIUNIDADNEGOCIOID ASC),
    CONSTRAINT XFKTCCJCCTRUNIDADNEGOCIO FOREIGN KEY (FIUNIDADNEGOCIOID) REFERENCES TCCJCCTRUNIDADNEGOCIO(FIUNIDADNEGOCIOID),
CONSTRAINT XFKTCCJCCTRTIPOFILA FOREIGN KEY (FITIPOFILAID) REFERENCES TCCJCCTRTIPOFILA(FITIPOFILAID)
)
GO



CREATE INDEX XIF1TCCJCCTRFILA ON TCCJCCTRFILA
( 
    FIUNIDADNEGOCIOID     ASC
)
GO



CREATE INDEX XIF2TCCJCCTRFILA ON TCCJCCTRFILA
( 
    FITIPOFILAID          ASC
)
GO



CREATE TABLE TACJCCTRTURNO
( 
    FIFECHA              INTEGER  NOT NULL ,
    FITURNOID            INTEGER  NOT NULL ,
    FIORIGENID           SMALLINT  NULL ,
    FCEMPNOID            CHAR(6)  NULL ,
    FIFILAID             SMALLINT  NULL ,
    FIUNIDADNEGOCIOID    SMALLINT  NULL ,
    FITURNOSEGUIMIENTO   INTEGER  NULL ,
    FIPRIORIDAD          SMALLINT  NULL ,
	FISTATUSTURNO        SMALLINT  NULL ,
	FIVIRTUAL            SMALLINT  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTACJCCTRTURNO PRIMARY KEY (FIFECHA ASC,FITURNOID ASC),
    CONSTRAINT XFKTCCJCCTRORIGEN FOREIGN KEY (FIORIGENID) REFERENCES TCCJCCTRORIGEN(FIORIGENID),
CONSTRAINT XFKTACJCCTRPOOLATENCION1 FOREIGN KEY (FCEMPNOID) REFERENCES TACJCCTRPOOLATENCION(FCEMPNOID),
CONSTRAINT XFKTCCJCCTRFILA FOREIGN KEY (FIFILAID,FIUNIDADNEGOCIOID) REFERENCES TCCJCCTRFILA(FIFILAID,FIUNIDADNEGOCIOID)
)
GO



CREATE INDEX XIF1TACJCCTRTURNO ON TACJCCTRTURNO
( 
    FIORIGENID            ASC
)
GO



CREATE INDEX XIF2TACJCCTRTURNO ON TACJCCTRTURNO
( 
    FCEMPNOID             ASC
)
GO



CREATE INDEX XIF3TACJCCTRTURNO ON TACJCCTRTURNO
( 
    FIFILAID              ASC,
    FIUNIDADNEGOCIOID     ASC
)
GO



CREATE TABLE TACJCCTRDETALLE
( 
    FIFECHA              INTEGER  NOT NULL ,
    FITURNOID            INTEGER  NOT NULL ,
    FITRANSACCION        SMALLINT  NULL ,
    FITOP                SMALLINT  NULL ,
    FICONCEPTO           SMALLINT  NULL ,
    FNIMPORTE            DECIMAL(12,2)  NULL ,
    FIIDTIPODIV          SMALLINT  NULL ,
    FDINICIO             DATETIME  NULL ,
    FDFIN                DATETIME  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTACJCCTRDETALLE PRIMARY KEY (FIFECHA ASC,FITURNOID ASC),
    CONSTRAINT XFKTACJCCTRTURNO1 FOREIGN KEY (FIFECHA,FITURNOID) REFERENCES TACJCCTRTURNO(FIFECHA,FITURNOID)
)
GO



CREATE UNIQUE INDEX XIF1TACJCCTRDETALLE ON TACJCCTRDETALLE
( 
    FIFECHA               ASC,
    FITURNOID             ASC
)
GO



CREATE TABLE TCCJCCTRCUALIDADES
( 
    FICUALIDADID         SMALLINT  NOT NULL ,
    FCDESCRIPCION        CHAR(50)  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTCCJCCTRCUALIDADES PRIMARY KEY (FICUALIDADID ASC)
)
GO



CREATE TABLE TACJCCTRCUALIDADPOOL
( 
    FCEMPNOID            CHAR(6)  NOT NULL ,
    FICUALIDADID         SMALLINT  NOT NULL ,
    FCVALOR              CHAR(50)  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTACJCCTRCUALIDADPOOL PRIMARY KEY (FCEMPNOID ASC,FICUALIDADID ASC),
    CONSTRAINT XFKTACJCCTRPOOLATENCION2 FOREIGN KEY (FCEMPNOID) REFERENCES TACJCCTRPOOLATENCION(FCEMPNOID),
CONSTRAINT XFKTCCJCCTRCUALIDADES FOREIGN KEY (FICUALIDADID) REFERENCES TCCJCCTRCUALIDADES(FICUALIDADID)
)
GO



CREATE INDEX XIF1TACJCCTRCUALIDADPOOL ON TACJCCTRCUALIDADPOOL
( 
    FCEMPNOID             ASC
)
GO



CREATE INDEX XIF2TACJCCTRCUALIDADPOOL ON TACJCCTRCUALIDADPOOL
( 
    FICUALIDADID          ASC
)
GO



CREATE TABLE TCCJCCTRESTADOTURNO
( 
    FISTATUSTURNOID      SMALLINT  NOT NULL ,
    FCDESCRIPCION        CHAR(50)  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTCCJCCTRESTADOTURNO PRIMARY KEY (FISTATUSTURNOID ASC)
)
GO



CREATE TABLE TACJCCTRHISTORICO
( 
    FIFECHA              INTEGER  NOT NULL ,
    FITURNOID            INTEGER  NOT NULL ,
    FISTATUSTURNOID      SMALLINT  NOT NULL ,
    FDACTUALIZACION      DATETIME  NULL ,
    FDFECHAINSERTA       DATETIME  NULL ,
    FCUSERINSERTA        CHAR(6)  NULL ,
    FDFECHAMODIF         DATETIME  NULL ,
    FCUSERMODIF          CHAR(6)  NULL ,
    CONSTRAINT XPKTACJCCTRHISTORICO PRIMARY KEY (FIFECHA ASC,FITURNOID ASC,FISTATUSTURNOID ASC),
    CONSTRAINT XFKTACJCCTRTURNO2 FOREIGN KEY (FIFECHA,FITURNOID) REFERENCES TACJCCTRTURNO(FIFECHA,FITURNOID),
CONSTRAINT XFKTCCJCCTRESTADOTURNO FOREIGN KEY (FISTATUSTURNOID) REFERENCES TCCJCCTRESTADOTURNO(FISTATUSTURNOID)
)
go



CREATE INDEX XIF1TACJCCTRHISTORICO ON TACJCCTRHISTORICO
( 
    FITURNOID             ASC,
    FIFECHA               ASC
)
go



CREATE INDEX XIF2TACJCCTRHISTORICO ON TACJCCTRHISTORICO
( 
    FISTATUSTURNOID       ASC
)
go